language: java
notifications:
  hipchat:
    rooms:
      secure: Ke9fMBOvj4NJeNw1+HBCNkMy+PdgQQoa8g+Rs5ldP9dIcPwSKFQFUha8v4N3NNVpDpJo1vStRfik5V974QkCHzWYvIJjDwh4LMNIJlSs+c9mMvVm3iYq/4ZY56hIxDyZe/wstao/FbLsl2BsSb0Tw3x2KgeuwZ+3CNZfqt5Pcuw=
deploy:
  provider: releases
  api_key:
    secure: X4UYV1nHCUMb//PFjZgbeCyQ7G9dAXH1/d+flGBTek/Om91sWR6GWwSDCfnK+LywUT0EXsDrSxry48xgo9whzaE2wdQR8gCcom/8vBGNvfyv7CXT+sHFlORF0+gD/WQpCVxPJW0ujbT+pSxoHzUhpJ3EnKwTFru76jWmFJZ+sdU=
  file: build/libs/xld-powercenter-plugin-1.0.1.jar
  on:
    repo: xebialabs-community/xld-powercenter-plugin
